services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    volumes:
      # Volúmen para que los datos no se borren al apagar el contenedor
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 12
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: django_app
    user: "${UID:-1000}:${GID:-1000}"
    # Mapeo de volumen para reflejar cambios de código en tiempo real sin reconstruir la imagen
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
    name: mysite_postgres_data