DEFAULT_USER_ID = 1
DEFAULT_REQUESTER_USER_ID = 2

TRIP_STATUS_ACTIVE = "activo"
TRIP_STATUS_FULL = "lleno"
TRIP_STATUS_CANCELLED = "cancelado"
TRIP_STATUS_FINALIZED = "finalizado"

REQUEST_STATUS_PENDING = "pendiente"
REQUEST_STATUS_ACCEPTED = "aceptada"
REQUEST_STATUS_REJECTED = "rechazada"
REQUEST_STATUS_CANCELLED = "cancelada"
REQUEST_STATUS_CANCELLED_BY_REQUESTER = "cancelada_por_solicitante"
REQUEST_STATUS_CANCELLED_BY_DRIVER = "cancelada_por_ofertante"
REQUEST_STATUS_CANCELLED_BY_OTHER_ACCEPTANCE = "cancelada_por_otra_aceptacion"
REQUEST_STATUS_CANCELLED_BY_FINALIZATION = "cancelada_por_finalizacion"
REQUEST_STATUS_FINALIZED = "finalizada"

PENDING_REQUEST_STATUS = REQUEST_STATUS_PENDING
ACCEPTED_REQUEST_STATUS = REQUEST_STATUS_ACCEPTED
REJECTED_REQUEST_STATUS = REQUEST_STATUS_REJECTED
CANCELLED_REQUEST_STATUS = REQUEST_STATUS_CANCELLED
CANCELLED_BY_FINALIZATION_REQUEST_STATUS = REQUEST_STATUS_CANCELLED_BY_FINALIZATION
FINALIZED_REQUEST_STATUS = REQUEST_STATUS_FINALIZED

NOTIFICATION_TYPE_TRIP_FINALIZED = "viaje_finalizado"

SCHEDULER_JOB_STATUS_RUNNING = "running"
SCHEDULER_JOB_STATUS_SUCCESS = "success"
SCHEDULER_JOB_STATUS_FAILED = "failed"

AUDIT_ACTOR_USER = "usuario"
AUDIT_ACTOR_SYSTEM = "sistema"

AUDIT_SOURCE_UI = "ui"
AUDIT_SOURCE_BACKEND = "backend"
AUDIT_SOURCE_SCHEDULER = "scheduler"

AUDIT_ACTION_FINALIZE_TRIP_MANUAL = "finalizar_viaje_manual"
AUDIT_ACTION_FINALIZE_TRIP_AUTOMATIC = "finalizar_viaje_automatico"

AUTO_FINALIZE_GRACE_MINUTES = 20
AUTO_FINALIZE_JOB_NAME = "auto_finalize_trips"
SCHEDULER_DEFAULT_INTERVAL_SECONDS = 60

ACTIVE_TRIP_STATUSES = {TRIP_STATUS_ACTIVE, TRIP_STATUS_FULL}
VALID_DIRECTIONS = {"to_cali", "to_jamundi"}
