DEFAULT_USER_ID = 1
DEFAULT_REQUESTER_USER_ID = 2

TRIP_STATUS_ACTIVE = "activo"
TRIP_STATUS_FULL = "lleno"
TRIP_STATUS_CANCELLED = "cancelado"
TRIP_STATUS_FINALIZED = "finalizado"

REQUEST_STATUS_PENDING = "pendiente"
REQUEST_STATUS_ACCEPTED = "aceptada"
REQUEST_STATUS_REJECTED = "rechazada"
REQUEST_STATUS_CANCELLED = "cancelada"

PENDING_REQUEST_STATUS = REQUEST_STATUS_PENDING
ACCEPTED_REQUEST_STATUS = REQUEST_STATUS_ACCEPTED
REJECTED_REQUEST_STATUS = REQUEST_STATUS_REJECTED
CANCELLED_REQUEST_STATUS = REQUEST_STATUS_CANCELLED

ACTIVE_TRIP_STATUSES = {TRIP_STATUS_ACTIVE, TRIP_STATUS_FULL}
VALID_DIRECTIONS = {"to_cali", "to_jamundi"}
